Update dependencies and template
ghga-de/metldata pull request #62
Opened 2024-02-22 13:27 UTC by dontseyit

This PR updates the dependencies and applies template changes. 

Since **get_event_loop()** is removed from **hexkit**, we need to refactor its use here as well. I tried to use the **event_loop** fixture provided by `pytest-asyncio` as the default behavior and marked tests with the required scopes, but it didn't work for some tests. Therefore, I refactored the **event_loop_fixture()** to set a new event loop for tests. However, I am not 100% sure about this solution; there might be a more ideal one.

2024-02-27 09:49 UTC, KerstenBreuer requested changes

2024-02-27 09:49 UTC, KerstenBreuer commented on .pyproject_generation/pyproject_custom.toml
> +    "ghga-event-schemas~=3.0.0",
Please have a look at our versioning guidelines: https://ghga.pages.hzdr.de/internal.ghga.de/main/developer/developer_sops/dsop012_python_dependency_management/#dependency-versioning-guidelines
```suggestion
    "hexkit[akafka,mongodb] >=2.1.1, <3",
    "ghga-service-commons[api,auth] >=2.0.1, <3",
    "ghga-event-schemas >=3.0.0, <4",
```

Linkml dependencies are an exception here as they are very unstable and are thus pinned.

2024-02-27 09:49 UTC, KerstenBreuer commented on tests/conftest.py
> +def event_loop_fixture():
I cannot comment on this. I think we should avoid depending on a shared event loop anyhow. Not sure why this was introduced. Might be a refactoring goal for later.

2024-03-26 14:49 UTC, mephenor approved these changes
I agree with Kersten on the event loop fixture, but there's nothing blocking so far.
You can go ahead and merge

2024-03-26 14:50 UTC, merged